-- ============================================================
--  GreenUnity — PostgreSQL
--  Conversión desde SQL Server
-- ============================================================

-- Si vas a crear la base de datos desde este archivo, ejecútalo
-- fuera de una transacción. Luego conéctate a la nueva base.
CREATE DATABASE greenunitydb;

-- ============================================================
-- 1. TIPO EVENTO
-- ============================================================
CREATE TABLE TipoEvento (
  id_tipo INTEGER PRIMARY KEY,
  nombre  VARCHAR(50) NOT NULL
);

INSERT INTO TipoEvento (id_tipo, nombre) VALUES
  (1, 'Limpieza'),
  (2, 'Reforestación'),
  (3, 'Taller'),
  (4, 'Reciclaje'),
  (5, 'Educación'),
  (6, 'Conservación');

-- ============================================================
-- 2. USUARIO
-- ============================================================
CREATE TABLE Usuario (
  id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre     VARCHAR(120) NOT NULL,
  email      VARCHAR(120) NOT NULL UNIQUE,
  contrasena VARCHAR(255) NOT NULL, -- bcrypt hash
  telefono   VARCHAR(9)   NOT NULL,
  rol        VARCHAR(15)  NOT NULL DEFAULT 'voluntario'
             CONSTRAINT CHK_rol CHECK (rol IN ('voluntario', 'admin', 'organizador')),
  activo     BOOLEAN      NOT NULL DEFAULT TRUE,
  creado_en  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 3. VOLUNTARIO
-- ============================================================
CREATE TABLE Voluntario (
  id_usuario INTEGER PRIMARY KEY
             REFERENCES Usuario(id_usuario) ON DELETE CASCADE
);

-- ============================================================
-- 4. ADMINISTRADOR
-- ============================================================
CREATE TABLE Administrador (
  id_usuario INTEGER PRIMARY KEY
             REFERENCES Usuario(id_usuario) ON DELETE CASCADE
);

-- ============================================================
-- 5. ORGANIZADOR
-- ============================================================
CREATE TABLE Organizador (
  id_organizador      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_organizacion VARCHAR(100) NOT NULL,
  id_usuario          INTEGER NOT NULL UNIQUE
                      REFERENCES Usuario(id_usuario) ON DELETE CASCADE
);

-- ============================================================
-- 6. EVENTO
-- ============================================================
CREATE TABLE Evento (
  id_evento      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre         VARCHAR(200) NOT NULL,
  descripcion    TEXT NOT NULL,
  fecha          DATE NOT NULL,
  hora           TIME NOT NULL,
  ubicacion      VARCHAR(300) NOT NULL,
  capacidad      INTEGER NOT NULL DEFAULT 30,
  inscritos      INTEGER NOT NULL DEFAULT 0, -- actualizado por trigger
  estado         VARCHAR(13) NOT NULL DEFAULT 'Próximo'
                 CONSTRAINT CHK_estado CHECK (estado IN ('Próximo', 'En curso', 'Finalizado', 'Cancelado')),
  archivado BOOLEAN NOT NULL DEFAULT FALSE,
  latitud        NUMERIC(10,7) NULL,  -- para Leaflet: marcador en el mapa
  longitud       NUMERIC(10,7) NULL,  -- para Leaflet: marcador en el mapa
  imagen_url     VARCHAR(500) NULL,   -- ruta /uploads/eventos/archivo.jpg
  id_tipo        INTEGER NOT NULL REFERENCES TipoEvento(id_tipo),
  id_organizador INTEGER NOT NULL REFERENCES Organizador(id_organizador)
);

-- ============================================================
-- 7. EVENTO_REQUISITO
-- ============================================================
CREATE TABLE EventoRequisito (
  id_requisito INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_evento    INTEGER NOT NULL REFERENCES Evento(id_evento) ON DELETE CASCADE,
  descripcion  VARCHAR(250) NOT NULL,
  orden        INTEGER NOT NULL DEFAULT 0
);

-- ============================================================
-- 8. INSCRIPCION
-- ============================================================
CREATE TABLE Inscripcion (
  id_inscripcion    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha_inscripcion DATE NOT NULL DEFAULT CURRENT_DATE,
  estado            VARCHAR(15) NOT NULL DEFAULT 'Próximo'
                    CONSTRAINT CHK_ins CHECK (estado IN ('Próximo', 'Finalizado', 'Cancelado')),
  id_voluntario     INTEGER NOT NULL REFERENCES Voluntario(id_usuario),
  id_evento         INTEGER NOT NULL REFERENCES Evento(id_evento),
  CONSTRAINT UQ_Inscripcion UNIQUE (id_voluntario, id_evento)
);

-- ============================================================
-- 9. ASISTENCIA
-- 1 inscripción = 1 asistencia
-- ============================================================
CREATE TABLE Asistencia (
  id_asistencia  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_inscripcion INTEGER NOT NULL UNIQUE
                 REFERENCES Inscripcion(id_inscripcion) ON DELETE CASCADE,
  asistio        BOOLEAN NOT NULL DEFAULT FALSE,
  fecha_registro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 10. CONFIGURACIÓN DE CERTIFICADOS
-- ============================================================
CREATE TABLE ConfigCertificado (
  id_config INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo    VARCHAR(100) NOT NULL,
  motivo    VARCHAR(200) NULL,
  color     VARCHAR(20)  NOT NULL DEFAULT 'success',
  umbral    INTEGER      NOT NULL,   -- nro de participaciones para emitir
  activo    BOOLEAN      NOT NULL DEFAULT TRUE
);

INSERT INTO ConfigCertificado (titulo, motivo, color, umbral) VALUES
  ('Primera participación', '1ra participación',  'success', 1),
  ('Participante Bronce I', '5 participaciones',  'primary', 5),
  ('Participante Plata I',  '10 participaciones', 'info',    10),
  ('Participante Oro I',    '20 participaciones', 'warning', 20);

-- ============================================================
-- 11. CERTIFICADO
-- ============================================================
CREATE TABLE Certificado (
  id_certificado        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo                VARCHAR(100) NOT NULL,
  motivo                VARCHAR(200) NULL,
  color                 VARCHAR(20)  NOT NULL DEFAULT 'success',
  cantidad_participacion INTEGER NOT NULL, -- cuántos eventos al momento de emitir
  fecha_emision         DATE NOT NULL DEFAULT CURRENT_DATE,
  archivo_url           VARCHAR(500) NULL,
  id_voluntario         INTEGER NOT NULL REFERENCES Voluntario(id_usuario),
  id_config             INTEGER NOT NULL REFERENCES ConfigCertificado(id_config)
);

-- ============================================================
-- 12. MENSAJE
-- Voluntario envía mensaje y puede ir a un Usuario destino
-- (Administrador u Organizador)
-- ============================================================
CREATE TABLE Mensaje (
  id_mensaje            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  asunto                VARCHAR(150) NOT NULL,
  mensaje               TEXT NOT NULL,
  fecha                 TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  leido                 BOOLEAN NOT NULL DEFAULT FALSE,
  leido_por_voluntario  BOOLEAN NOT NULL DEFAULT FALSE,
  respondido            BOOLEAN NOT NULL DEFAULT FALSE,
  id_voluntario         INTEGER NOT NULL REFERENCES Voluntario(id_usuario),
  id_usuario_destino    INTEGER NOT NULL REFERENCES Usuario(id_usuario),
  id_evento             INTEGER NULL REFERENCES Evento(id_evento)
);

-- ============================================================
-- 13. NOTIFICACION
-- Emisor: Usuario (admin u organizador)
-- Destino: voluntarios inscritos al evento
-- ============================================================
CREATE TABLE Notificacion (
  id_notificacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo          VARCHAR(200) NOT NULL,
  mensaje         TEXT NOT NULL,
  fecha           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  id_usuario      INTEGER NOT NULL REFERENCES Usuario(id_usuario),
  id_evento       INTEGER NOT NULL REFERENCES Evento(id_evento)
);

-- ============================================================
-- 14. CONTACTO
-- Formulario público, independiente
-- ============================================================
CREATE TABLE Contacto (
  id_contacto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre      VARCHAR(100) NOT NULL,
  telefono    VARCHAR(9) NOT NULL,
  email       VARCHAR(100) NOT NULL,
  asunto      VARCHAR(150) NOT NULL,
  mensaje     TEXT NOT NULL,
  fecha       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  leido       BOOLEAN NOT NULL DEFAULT FALSE
);

-- ============================================================
-- 15. RespuestaMensaje
-- ============================================================
CREATE TABLE RespuestaMensaje (
  id_respuesta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_mensaje   INTEGER NOT NULL
               REFERENCES Mensaje(id_mensaje) ON DELETE CASCADE,
  texto        TEXT NOT NULL,
  fecha        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  id_usuario   INTEGER NOT NULL    -- admin u organizador que responde
               REFERENCES Usuario(id_usuario)
);

-- ============================================================
-- 16. NotificacionLeida
-- ============================================================
CREATE TABLE NotificacionLeida (
  id_notificacion INTEGER NOT NULL REFERENCES Notificacion(id_notificacion) ON DELETE CASCADE,
  id_voluntario   INTEGER NOT NULL REFERENCES Voluntario(id_usuario) ON DELETE CASCADE,
  fecha_lectura   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_NotificacionLeida PRIMARY KEY (id_notificacion, id_voluntario)
);

-- ============================================================
-- ÍNDICES
-- ============================================================
CREATE INDEX IX_Inscripcion_Vol       ON Inscripcion(id_voluntario);
CREATE INDEX IX_Inscripcion_Ev        ON Inscripcion(id_evento);
CREATE INDEX IX_Asistencia_Ins        ON Asistencia(id_inscripcion);
CREATE INDEX IX_Notif_Evento          ON Notificacion(id_evento);
CREATE INDEX IX_Mensaje_Vol           ON Mensaje(id_voluntario);
CREATE INDEX IX_Mensaje_Destino       ON Mensaje(id_usuario_destino);
CREATE INDEX IX_Contacto_Leido        ON Contacto(leido);
CREATE INDEX IX_RespuestaMensaje_Msg  ON RespuestaMensaje(id_mensaje);
CREATE INDEX IX_NotifLeida_Vol        ON NotificacionLeida(id_voluntario);

-- ============================================================
-- TRIGGER 1: Evento.inscritos automático
-- ============================================================
CREATE OR REPLACE FUNCTION fn_tr_inscripcion_count()
RETURNS TRIGGER AS $$
DECLARE
  v_evento_id INTEGER;
BEGIN
  IF TG_OP IN ('INSERT', 'UPDATE') THEN
    v_evento_id := NEW.id_evento;
    UPDATE Evento
    SET inscritos = (
      SELECT COUNT(*)
      FROM Inscripcion
      WHERE id_evento = v_evento_id
        AND estado <> 'Cancelado'
    )
    WHERE id_evento = v_evento_id;
  END IF;

  IF TG_OP IN ('DELETE', 'UPDATE') THEN
    IF TG_OP = 'UPDATE' AND NEW.id_evento IS NOT DISTINCT FROM OLD.id_evento THEN
      NULL;
    ELSE
      v_evento_id := OLD.id_evento;
      UPDATE Evento
      SET inscritos = (
        SELECT COUNT(*)
        FROM Inscripcion
        WHERE id_evento = v_evento_id
          AND estado <> 'Cancelado'
      )
      WHERE id_evento = v_evento_id;
    END IF;
  END IF;

  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS TR_Inscripcion_Count ON Inscripcion;
CREATE TRIGGER TR_Inscripcion_Count
AFTER INSERT OR DELETE OR UPDATE ON Inscripcion
FOR EACH ROW
EXECUTE FUNCTION fn_tr_inscripcion_count();

-- ============================================================
-- TRIGGER 2: marcar Mensaje.respondido = TRUE al insertar respuesta,
--            y resetear leido_por_voluntario = FALSE (hay nueva resp.)
-- ============================================================
CREATE OR REPLACE FUNCTION fn_tr_respuesta_mensaje_insert()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE Mensaje
  SET respondido = TRUE,
      leido_por_voluntario = FALSE
  WHERE id_mensaje = NEW.id_mensaje;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS TR_RespuestaMensaje_Insert ON RespuestaMensaje;
CREATE TRIGGER TR_RespuestaMensaje_Insert
AFTER INSERT ON RespuestaMensaje
FOR EACH ROW
EXECUTE FUNCTION fn_tr_respuesta_mensaje_insert();

-- ============================================================
-- TRIGGER 3: Certificado automático por asistencia
-- ============================================================
CREATE OR REPLACE FUNCTION fn_tr_asistencia_certificado()
RETURNS TRIGGER AS $$
DECLARE
  v_total_asistencias INTEGER;
  v_id_voluntario INTEGER;
  rec RECORD;
BEGIN
  IF TG_OP = 'UPDATE' AND NEW.asistio = TRUE AND OLD.asistio = FALSE THEN
    SELECT ins.id_voluntario
      INTO v_id_voluntario
    FROM Inscripcion ins
    WHERE ins.id_inscripcion = NEW.id_inscripcion;

    SELECT COUNT(*)
      INTO v_total_asistencias
    FROM Asistencia a
    JOIN Inscripcion ins ON a.id_inscripcion = ins.id_inscripcion
    WHERE ins.id_voluntario = v_id_voluntario
      AND a.asistio = TRUE;

    FOR rec IN
      SELECT id_config, umbral, titulo, motivo, color
      FROM ConfigCertificado
      WHERE activo = TRUE
        AND umbral <= v_total_asistencias
      ORDER BY umbral
    LOOP
      IF NOT EXISTS (
        SELECT 1
        FROM Certificado c
        WHERE c.id_voluntario = v_id_voluntario
          AND c.id_config = rec.id_config
      ) THEN
        INSERT INTO Certificado
          (titulo, motivo, color, cantidad_participacion,
           fecha_emision, id_voluntario, id_config)
        VALUES
          (rec.titulo, rec.motivo, rec.color, v_total_asistencias,
           CURRENT_DATE, v_id_voluntario, rec.id_config);
      END IF;
    END LOOP;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS TR_Asistencia_Certificado ON Asistencia;
CREATE TRIGGER TR_Asistencia_Certificado
AFTER UPDATE ON Asistencia
FOR EACH ROW
EXECUTE FUNCTION fn_tr_asistencia_certificado();
